// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEAnisDQ5lMhHhhb-OIMbzV9EyS4zksQ',
    appId: '1:31632121234:android:debac847255e039a05f54b',
    messagingSenderId: '31632121234',
    projectId: 'evently-app-61105',
    storageBucket: 'evently-app-61105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNPLpxqcJVpaYmKC3L5C07Z1wUobpRLw',
    appId: '1:31632121234:ios:a97c5ad7ff8f2a7805f54b',
    messagingSenderId: '31632121234',
    projectId: 'evently-app-61105',
    storageBucket: 'evently-app-61105.firebasestorage.app',
    androidClientId: '31632121234-fle31e7f5vd2s48t9h7cvmtjasf0t6n1.apps.googleusercontent.com',
    iosClientId: '31632121234-1i1p4eduismmq4q0hpsjj4omo9jq52ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

}